base_url = "https://quirky-perlman-34d0da.netlify.com"
title = "Light Speed Refined"
description = "Zola theme with a perfect Lighthouse score, themed with Premier"

compile_sass = true
generate_feed = true

[extra]

seo = true
author = "Shanoa Ice"
ogimage = "lightning.png"

zola = true
cloudflare = true
maintained_with_love = true

footer_links = [
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/atom.xml", name = "RSS"},
    {url = "https://github.com/carpetscheme/lightspeed", name = "Source on Github"},
]

