name = "refined-lightspeed"
description = "Zola theme with a perfect Lighthouse score"
license = "MIT"
homepage = "https://github.com/shanoaice/refined-lightspeed"
min_version = "0.10.0"
demo = "https://refined-lightspeed.pages.dev/"

[author]
name = "Shanoa Ice"
homepage = "https://github.com/shanoaice"

[original]
name = "El Carpet"
homepage = "https://github.com/carpetscheme"
repo = "https://github.com/carpetscheme/lightspeed"

